version: '3.8'

services:
  web:
    build: .
    container_name: 'web'
    ports:
      - 8000:8000
    volumes:
      - .:/app

  rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: 'mq'
    ports:
      - 5672:5672
      
  # celery_instance_A:
  #   build:
  #       context: .
  #   container_name: 'celery_instance_A'
  #   command: bash -c "celery -A [celery worker project] worker --loglevel=info"
  #   depends_on:
  #     - rabbitmq
  #   network:
  #     - simulated_network
  #
  # celery_instance_B:
  #   build:
  #       context: .
  #   container_name: 'celery_instance_B'
  #   command: bash -c "celery -A [celery worker project] worker --loglevel=info"
  #   depends_on:
  #     - rabbitmq
  #   network:
  #     - simulated_network
  #
volumes:
  data:
